### PR TITLE
added instructions to setup free bigquery account

### PR DESCRIPTION
**Pull request by gongahkia**
have followed up on [this issue](https://github.com/OSSPhilippines/personal-well-being-dashboard/issues/18#event-12876130820) with this PR

### CODE REVIEW

**Comment by philgerardsoto** [comment]
Hi @gongahkia thank you for your PR. This is really helpful.

I committed to the same branch my suggested edits. Kindly let me know what you think.

Also, I'll open an issue re aligning documentation for Gmail API and BigQuery API. Currently all Gmail API documentation is based on https://github.com/jeremyephron/simplegmail but they can belong to just one Google Cloud Console project for simplicity.

**Comment by gongahkia** [comment]
Hi @philgerardsoto, the updated version looks great! Thank you for tidying up the instructions and clarifying where I was being vague! 

Roger that, sounds good. Let me familiarize myself with the project first, I think you can consider opening that issue to anyone else who wants to give it a go?

**Comment by philgerardsoto** [comment]
Thanks @gongahkia! I'll merge this for now. Please feel free to look at the other open PRs and issues for now! Would you happen to speak Filipino? We have intro Youtube vids re the project but it's mostly in Filipino (language used in the Philippines)

**Review by philgerardsoto — APPROVED** [review]

**Comment by gongahkia** [comment]
@philgerardsoto aaah I don't, but I have a friend who does and he's a programmer as well. I'll get him to take a look and explain to me as well as contribute further to resolve other issues if that's okay with you! :)

**Comment by philgerardsoto** [comment]
Sure @gongahkia! We're just starting, and definitely lots more to do. I'll try to record an English version when time permits. I saw some other prospective contributors some days ago.

**Pull request merged**
