### PR TITLE
Sai/gmail extraction

### PR DESCRIPTION
**Pull request by sairilseb-me**
## Created a gmail extractor

- Created an email extractor that will extract data from Gcash and Unionbank, you can remove the parameter if you want to get all the messages.

### CODE REVIEW

**Comment by philgerardsoto** [comment]
Hi @sairilseb-me thanks for starting on this task. I was able to run your `simple_gmail_sai.py` file, and it works! I attached a screenshot of my result.

Image 5-19-24 at 8 25 PM

Some suggestions:

1. In `gmail_downloader.py` under the simplegmail folder, we have a process_messages function. I suggest we improve this by incorporating your code regarding parameter filtering.

2. Also in `gmail_downloader.py`, the `message_data` dictionary contains just a few of the fields available via the API:

```
id
sender
recipient
subject
plain
html
date
```

I suggest we include all available fields since we're using an ELT approach. We can print all available attributes of the message object, and include all of these fields in the `message_data` dictionary.

3. In `gmail_downloader_sample.py` in the root folder, there is there is a function to generate monthly date ranges that can serve as filter in your parameter filtering code. Please feel free to incorporate this either on `gmail_downloader.py` under the simplegmail folder or on a file on the root folder.
 
4. It would also be good to check the parameter filtering based on domains and keywords. I was able to get hello@gcash.com emails but not no-reply@gcash.com emails.

Note for observers in this PR: you have to add an 'attachments' folder in the root directory for `gmail_downloader.py` to work.

Kindly reach out for any questions. Or other suggested approaches. Thank you @sairilseb-me!

**Comment by sairilseb-me** [comment]
Suggestion 1 done.

- Issue: Having issue saving attachments, currently the method `save_attachments` is commented

commit # [f5f079a](https://github.com/OSSPhilippines/personal-well-being-dashboard/pull/16/commits/f5f079a89d24bd138e1833e18021efef3ded85f7)

**Comment by sairilseb-me** [comment]
## Updates

- Updated `gmail.py` to have additional parameter `start_date` and `end_date` and concat to `query`
- fixed issue of not getting data from no-replay@domains

**Comment by philgerardsoto** [comment]
Hi @sairilseb-me thank you. I mentioned this in our private chat but commenting here as well for visibility:

When I run the code locally, I still don't get the Unionbank emails. I think we should edit the query condition based on https://support.google.com/mail/answer/7190

Also, I suggest we don't edit gmail.py, and put the revision on the other files. gmail.py is based on the simplegmail repository so we want to keep it untouched as much as possible.

Thank you!

**Comment by philgerardsoto** [comment]
Also, code simplification suggestion by Copilot:

# Construct query
query = ' OR '.join([f"from: {domain}" for domain in domains] + [f"subject: {keyword}" for keyword in keywords])

**Comment by philgerardsoto** [comment]
Nice work @sairilseb-me! I'm now able to get both GCash and Unionbank emails.

I pushed two minor commits, and will merge this now.

Next related task to this is for us to use Airflow and/or dlt.

**Review by philgerardsoto — APPROVED** [review]
Thanks again @sairilseb-me nicely done!

**Pull request merged**
